### ISSUE TITLE
add word: cast

### ISSUE THREAD

**Issue by cloutdictionary** [cat-ico/cloutdictionary#16]
**Definition**: ## Verb
To promote BitClout content

## Noun
Promoted BitClout content
**Usage**: ## Verb
I casted something, and @diamondhands wound up reclouting it!!

## Noun
Have you seen that cast on cloutcast.io? The promotion owner is giving people 10$ to reclout this!

**Comment by Zyther** [comment]
@cloutdictionary you need to `\n` after `**Definition**:` and `**Usage**:` so it looks like below ;) 

**Definition**: 
## Verb
To promote BitClout content
 
## Noun
Promoted BitClout content


**Usage**: 
## Verb
I casted something, and @diamondhands wound up reclouting it!!
 
## Noun
Have you seen that cast on cloutcast.io? The promotion owner is giving people 10$ to reclout this!
